import { expect, test } from "bun:test";
import {
  caddyfileSites,
  customFileProblems,
  normalizeToken,
  proxyPaths,
  redactSecrets,
  renderMainCaddyfile,
  wildcardParents,
} from "../src/domain/managed-proxy";
import { parseHostConfig } from "../src/config";
import {
  adaptedSiteAddresses,
  issuerCas,
  protectedDifferences,
} from "../src/domain/caddy-config";

const settings = (proxy: Record<string, unknown> = {}) =>
  parseHostConfig({ proxy: { caddy: "/usr/local/bin/caddy", ...proxy } })
    .proxy!;

test("one wildcard per parent covers every hostname this Host will serve, and a Preview's flat name needs none of its own", () => {
  expect(
    wildcardParents([
      "rig.b-relay.com",
      "pantry.b-relay.com",
      "pantry-feat-x-1a2b3c4d.b-relay.com",
      "melody.b-relay.com",
      "api.melody.b-relay.com",
      "api-feat-x-1a2b3c4d.melody.b-relay.com",
      "private.share.b-relay.com",
      "dev.vitals.b-relay.com",
    ]),
  ).toEqual([
    "*.b-relay.com",
    "*.melody.b-relay.com",
    "*.share.b-relay.com",
    "*.vitals.b-relay.com",
  ]);
});

test("a name with no certificate of its own, or whose parent is a public suffix, gets no wildcard", () => {
  expect(
    wildcardParents([
      "b-relay.com",
      "http://plain.example.com",
      "127.0.0.1",
      "http://127.0.0.1:8080",
      "demo.localhost",
      "*.already.example.com",
      "https://App.Example.com:8443",
    ]),
  ).toEqual(["*.example.com"]);
});

test("the site scanner finds top-level site addresses and skips the global block, snippets, imports, matchers and comments", () => {
  const text = [
    "# a comment {",
    "{",
    "  admin off",
    "}",
    "(backend_errors) {",
    "  handle_errors {",
    "    respond 502",
    "  }",
    "}",
    "import other.caddy",
    "one.example.com, two.example.com {",
    "  @api path /api",
    "  handle @api {",
    "    reverse_proxy 127.0.0.1:1",
    "  }",
    "}",
    "*.share.example.com {  # wildcard",
    "  abort",
    "}",
  ].join("\n");
  expect(caddyfileSites(text)).toEqual([
    "one.example.com",
    "two.example.com",
    "*.share.example.com",
  ]);
});

test("a generation's main file names only its own files, the socket, storage and one ACME issuer with the token as a placeholder", () => {
  const paths = proxyPaths("/r");
  const text = renderMainCaddyfile({
    settings: settings({
      tls: { email: "ops@example.com" },
      site: ["import backend_errors"],
    }),
    paths,
    generation: "/r/caddy/generations/g1",
    hostnames: ["app.example.com", "api.app.example.com"],
    customSites: [],
  });
  expect(text).toBe(
    [
      "# Generated by Rig from Host config. Do not edit: your sites go in /r/proxy/custom.caddy, your global options in /r/proxy/custom-global.caddy.",
      "{",
      '\tadmin "unix//r/caddy/admin.sock|0600"',
      "\tpersist_config off",
      "\tstorage file_system /r/caddy/data",
      "\thttp_port 80",
      "\thttps_port 443",
      "\temail ops@example.com",
      "\tcert_issuer acme https://acme-v02.api.letsencrypt.org/directory {",
      "\t\tdns cloudflare {file./r/auth/acme-dns.token}",
      "\t\tresolvers 1.1.1.1 1.0.0.1",
      "\t}",
      "\tlog default {",
      "\t\toutput file /r/caddy/caddy.log {",
      "\t\t\troll_size 10MiB",
      "\t\t\troll_keep 5",
      "\t\t}",
      "\t}",
      "\timport /r/caddy/generations/g1/custom-global.caddy",
      "}",
      "import /r/caddy/generations/g1/custom.caddy",
      "",
      "# One certificate per parent of a served hostname. A name below one of these that no site serves is refused.",
      "*.app.example.com, *.example.com {",
      "\tabort",
      "}",
      "",
      "import /r/caddy/generations/g1/routes.caddy",
      "",
    ].join("\n"),
  );
});

test("high ports stay on 127.0.0.1, internal certificates never touch the keychain, hostname mode has no wildcards, and a custom wildcard replaces Rig's", () => {
  const paths = proxyPaths("/r");
  const local = renderMainCaddyfile({
    settings: settings({
      ports: { http: 28080, https: 28443 },
      tls: { ca: "internal", certificates: "hostname" },
    }),
    paths,
    generation: "/r/caddy/generations/g2",
    hostnames: ["app.example.com"],
    customSites: [],
  });
  expect(local).toContain("\tdefault_bind 127.0.0.1\n");
  expect(local).toContain("\tlocal_certs\n\tskip_install_trust\n");
  expect(local).not.toContain("cert_issuer");
  expect(local).not.toContain("acme-dns.token");
  expect(local).not.toContain("abort");

  const staged = renderMainCaddyfile({
    settings: settings({ tls: { ca: "letsencrypt-staging" } }),
    paths,
    generation: "/r/caddy/generations/g3",
    hostnames: ["app.example.com", "x.share.example.com"],
    customSites: ["*.share.example.com"],
  });
  expect(staged).toContain(
    "cert_issuer acme https://acme-staging-v02.api.letsencrypt.org/directory {",
  );
  expect(staged).not.toContain("default_bind");
  expect(staged).toContain("*.example.com {\n\tabort\n}");
  expect(staged).not.toContain("*.share.example.com,");

  expect(() =>
    renderMainCaddyfile({
      settings: settings(),
      paths: proxyPaths("/r with space"),
      generation: "/r with space/caddy/generations/g4",
      hostnames: [],
      customSites: [],
    }),
  ).toThrow(expect.objectContaining({ code: "PROXY_PATH" }));
});

test("a token is trimmed and must be one unbroken run of token characters; a malformed one is refused without echoing it", () => {
  const synthetic = "Syn_thetic-Token-0123456789abcdefABCDEF";
  expect(normalizeToken(`  ${synthetic}\n`)).toBe(synthetic);
  for (const bad of [
    "short",
    `${synthetic} trailing-word`,
    `"${synthetic}"`,
    `${synthetic}\n${synthetic}`,
    "",
  ]) {
    let error: unknown;
    try {
      normalizeToken(bad);
    } catch (caught) {
      error = caught;
    }
    expect(error).toMatchObject({ code: "PROXY_TOKEN" });
    expect(JSON.stringify(error)).not.toContain("Syn_thetic");
    expect(String((error as Error).message)).not.toContain("Syn_thetic");
  }
});

test("redaction removes the token's value and anything Caddy quotes after 'token', including a malformed paste", () => {
  const token = "Syn_thetic-Token-0123456789abcdefABCDEF";
  const caddy = `provision dns.providers.cloudflare: API token '${token}\n' appears invalid; ensure it's correctly entered`;
  const redacted = redactSecrets(caddy, [token]);
  expect(redacted).not.toContain("Syn_thetic");
  expect(redacted).toContain("[redacted]");
  // A value Rig does not know, quoted by the plugin, is still hidden.
  expect(
    redactSecrets("API token 'Other_synthetic_value_42' appears invalid", []),
  ).toBe("API token '[redacted]' appears invalid");
  // Output without a token is left alone.
  expect(redactSecrets("Valid configuration", [token])).toBe(
    "Valid configuration",
  );
});

test("Rig accepts exactly the token forms caddy-dns/cloudflare v0.2.4 accepts, so the plugin never quotes a token it rejects", () => {
  const classic = "A".repeat(35);
  expect(normalizeToken(classic)).toBe(classic);
  expect(normalizeToken("b".repeat(50))).toBe("b".repeat(50));
  expect(normalizeToken(`cfut_${"x".repeat(32)}`)).toBe(
    `cfut_${"x".repeat(32)}`,
  );
  expect(normalizeToken(`cfat_${"y_-".repeat(20)}`)).toBe(
    `cfat_${"y_-".repeat(20)}`,
  );
  for (const rejected of [
    "A".repeat(34),
    "A".repeat(51),
    `cfxx_${"x".repeat(60)}`,
    `cfut_${"x".repeat(40)}.`,
    `${"A".repeat(40)}=`,
  ])
    expect(() => normalizeToken(rejected)).toThrow(
      expect.objectContaining({ code: "PROXY_TOKEN" }),
    );
});

test("custom files may import only their own snippets, and read no file through placeholders or certificate paths", () => {
  const root = "/r";
  expect(
    customFileProblems(
      {
        sites:
          "(errors) {\n\trespond 502\n}\na.test {\n\timport errors\n\ttls internal {\n\t\ton_demand\n\t}\n\ttls /r/certs/a.pem /r/certs/a.key\n}\n",
        global: "servers {\n\ttimeouts {\n\t\tidle 2m\n\t}\n}\n",
      },
      root,
    ),
  ).toEqual([]);
  expect(
    customFileProblems(
      {
        sites: [
          "import /etc/caddy/more.caddy",
          "a.test {",
          "\timport missing",
          '\trespond "{file./etc/passwd}"',
          "\ttls /etc/cert.pem /etc/key.pem",
          "\ttls {",
          "\t\tca_root /etc/ssl/root.pem",
          "\t}",
          "}",
        ].join("\n"),
        global: "import global.caddy\n",
      },
      root,
    ),
  ).toEqual([
    { file: "sites", line: 1, problem: "imports /etc/caddy/more.caddy" },
    { file: "sites", line: 3, problem: "imports missing" },
    {
      file: "sites",
      line: 4,
      problem: "reads a file through a {file.*} placeholder",
    },
    {
      file: "sites",
      line: 5,
      problem: "names certificate files outside the Rig root",
    },
    {
      file: "sites",
      line: 7,
      problem: "names files outside the Rig root in ca_root",
    },
    { file: "global", line: 1, problem: "imports global.caddy" },
  ]);
});

test("quoting, '..' and the other directives that load certificate files cannot read outside the Rig root", () => {
  const problems = customFileProblems(
    {
      sites: [
        "`import` `/etc/caddy/more.caddy`",
        "a.test {",
        "\ttls /r/../etc/c.pem /r/../etc/k.pem",
        "\treverse_proxy https://b {",
        "\t\ttransport http {",
        "\t\t\ttls_client_auth /etc/c.pem /etc/k.pem",
        "\t\t\ttls_trusted_ca_certs /etc/ca.pem",
        "\t\t}",
        "\t}",
        "\ttls {",
        "\t\tclient_auth {",
        "\t\t\ttrust_pool file /etc/ca.pem",
        "\t\t}",
        "\t}",
        "}",
      ].join("\n"),
      global:
        "pki {\n\tca local {\n\t\troot {\n\t\t\tcert /etc/root.pem\n\t\t\tkey /etc/root.key\n\t\t}\n\t}\n}\n",
    },
    "/r",
  );
  expect(problems.map((problem) => `${problem.file}:${problem.line}`)).toEqual([
    "sites:1",
    "sites:3",
    "sites:6",
    "sites:7",
    "sites:12",
    "global:4",
    "global:5",
  ]);
  // Relative certificate paths resolve under the Rig root, where Caddy runs, and stay allowed.
  expect(
    customFileProblems(
      { sites: "a.test {\n\ttls certs/a.pem certs/a.key\n}\n", global: "" },
      "/r",
    ),
  ).toEqual([]);
});

test("Caddy's JSON tells the sites it serves, what Rig protects, and the CAs it issues from", () => {
  const config = {
    admin: { listen: "unix//r/caddy/admin.sock|0600" },
    storage: { module: "file_system", root: "/r/caddy/data" },
    apps: {
      http: {
        http_port: 80,
        https_port: 443,
        servers: {
          srv0: {
            listen: [":443"],
            routes: [
              { match: [{ host: ["a.example.test", "*.example.test"] }] },
            ],
          },
          srv1: {
            listen: [":80"],
            routes: [{ match: [{ host: ["plain.example.test"] }] }],
          },
        },
      },
      tls: {
        automation: {
          policies: [
            {
              issuers: [
                {
                  module: "acme",
                  ca: "https://acme-v02.api.letsencrypt.org/directory",
                },
              ],
            },
          ],
        },
      },
    },
  };
  expect(adaptedSiteAddresses(config)).toEqual([
    "a.example.test",
    "*.example.test",
    "http://plain.example.test",
  ]);
  const expected = {
    admin: "unix//r/caddy/admin.sock|0600",
    storage: "/r/caddy/data",
    httpPort: 80,
    httpsPort: 443,
  };
  expect(protectedDifferences(config, expected)).toEqual([]);
  expect(
    protectedDifferences(
      {
        ...config,
        admin: { listen: "localhost:2999" },
        apps: {
          ...config.apps,
          http: { ...config.apps.http, https_port: 8443 },
        },
      },
      expected,
    ),
  ).toEqual(["admin", "https_port"]);
  // No site, no HTTP app: nothing listens, so the ports cannot differ.
  expect(
    protectedDifferences(
      { admin: config.admin, storage: config.storage },
      expected,
    ),
  ).toEqual([]);
  expect(issuerCas(config)).toEqual([
    "https://acme-v02.api.letsencrypt.org/directory",
  ]);
  expect(issuerCas({})).toEqual([]);
});
