import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

/** The module scripts/generate-recipe-files.ts writes to src/recipes/generated-files.ts: the text of every file in
 * src/recipes/files/, by name. Read from the source tree, so it runs from a checkout of Rig, never from a built binary. */
export async function renderRecipeFileModule(): Promise<string> {
  const directory = join(import.meta.dir, "files");
  const names = (await readdir(directory)).sort();
  const entries = await Promise.all(
    names.map(
      async (name) =>
        `  ${JSON.stringify(name)}: ${JSON.stringify(await readFile(join(directory, name), "utf8"))},`,
    ),
  );
  return `// Generated by \`bun run recipe-files\` from src/recipes/files/; a test holds it to those files. Do not edit.\nexport const RECIPE_FILE_TEXT = {\n${entries.join("\n")}\n} as const;\n`;
}
